Nutritionist/Nutritionist.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nutritionist.Web.Infrastructure;
using ArticleListModel = Nutritionist.Core.Models.Article.List;
using ArticleDetailModel = Nutritionist.Core.Models.Article.Detail;
using ArticleUpdateModel = Nutritionist.Core.Models.Article.Update;
using Nutritionist.Core.Models;
using Nutritionist.Core.Models.ResponseModels;
using AutoMapper;
using Nutritionist.Web.Models;
using Microsoft.AspNetCore.Http;

namespace Nutritionist.Web.Controllers
{
    public class ArticleController : BaseController
    {
        public ArticleController(IMapper mapper) : base(mapper)
        {
        }

        public IActionResult Detail(int id)
        {
            var articleDetailBaseModels = Get<ArticleDetailModel>(MyApiRequestModel.GetArticleDetail, false, id.ToString());
            var checkArticleBaseResponseError = CheckBaseControllerError(articleDetailBaseModels);
            if (checkArticleBaseResponseError == null)
            {
                return View(ReadOnlyValues.ArticleDetailViewPath, articleDetailBaseModels.tobject);
            }
            else
            {
                return Error(checkArticleBaseResponseError);
            }
        }
        public IActionResult NutritionistArticleList(String nutritionistId)
        {
            var nutritionistArticleListModels = Get<List<ArticleListModel>>(MyApiRequestModel.GetNutritionistArticlesList, false, nutritionistId);
            var checkNutArticleListBaseResponseError = CheckBaseControllerError(nutritionistArticleListModels);

            if (checkNutArticleListBaseResponseError == null)
            {
                return View(ReadOnlyValues.NutritionistArticlesViewPath, nutritionistArticleListModels.tobject);
            }
            else
            {
                return Error(checkNutArticleListBaseResponseError);
            }
        }
        public IActionResult List()
        {
            var articleListBaseModels = Get<List<ArticleListModel>>(MyApiRequestModel.GetArticlesList, false);
            var checkArticlesBaseResponseError = CheckBaseControllerError(articleListBaseModels);
            if (checkArticlesBaseResponseError == null)
            {
                return View(ReadOnlyValues.ArticleListViewPath, articleListBaseModels.tobject);
            }
            else
            {
                return Error(checkArticlesBaseResponseError);
            }
        }

        [HttpGet]
        public IActionResult Edit(String id)
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            var articleDetailResponse = Get<ArticleDetailModel>(MyApiRequestModel.GetArticleDetail, false, id);
            var checkArticleDetailBaseControllerError = CheckBaseControllerError(articleDetailResponse);
            if (checkArticleDetailBaseControllerError == null)
            {
                var articleUpdateModel = mapper.Map<ArticleDetailModel, ArticleUpdateModel>(articleDetailResponse.tobject);
                return View(ReadOnlyValues.ArticleEditViewPath, articleUpdateModel);
            }
            else
            {
                return Error(checkArticleDetailBaseControllerError);
            }
        }

        [HttpPost]
        public IActionResult Edit(ArticleUpdateModel articleUpdateModel)
        {
            if (ModelState.IsValid)
            {
                var editRes = PostMultipartForm<bool>(MyApiRequestModel.PostArticleEdit, articleUpdateModel,true);
                var checkEditBaseControllerError = CheckBaseControllerError(editRes);
                if (checkEditBaseControllerError == null)
                {
                    return Detail(articleUpdateModel.Id);
                }
                else
                {
                    return Error(checkEditBaseControllerError);
                }
            }
            else
            {
                return Edit(articleUpdateModel.Id.ToString());
            }

        }
        public IActionResult Delete(String id)
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            else
            {
                var articleDeleteResponse = Delete<bool>(MyApiRequestModel.DeleteArticle, true, id);
                var checkArticleDeleteBaseControllerError = CheckBaseControllerError(articleDeleteResponse);
                if (checkArticleDeleteBaseControllerError == null)
                {

                    return NutritionistArticleList(nutritionistId.Value.ToString());
                }
                else
                {
                    return Error(checkArticleDeleteBaseControllerError);
                }
            }

        }
    }
}

Nutritionist/Nutritionist.Web/Controllers/NutritionistController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nutritionist.Web.Infrastructure;
using NutritionistDetailModel = Nutritionist.Core.Models.Nutritionist.Detail;
using NutritionistUpdateModel = Nutritionist.Core.Models.Nutritionist.Update;
using ArticleDetailModel = Nutritionist.Core.Models.Article.Detail;
using NutritionistListModel = Nutritionist.Core.Models.Nutritionist.List;
using NutritionistInsertModel = Nutritionist.Core.Models.Nutritionist.Insert;
using CommentListModel = Nutritionist.Core.Models.Comment.List;
using CommentInsertModel = Nutritionist.Core.Models.Comment.Insert;
using ArticleListModel = Nutritionist.Core.Models.Article.List;
using ArticleInsertModel = Nutritionist.Core.Models.Article.Insert;
using UserListModel = Nutritionist.Core.Models.User.List;
using UserLoginModel = Nutritionist.Core.Models.User.Login;
using UserDetailModel = Nutritionist.Core.Models.User.Detail;
using UserInsertModel = Nutritionist.Core.Models.User.Insert;
using Nutritionist.Core.Models;
using Nutritionist.Core.Models.ResponseModels;
using Nutritionist.Web.Models.ApiModelsCombines;
using Nutritionist.Web.Models;
using AutoMapper;
using Microsoft.AspNetCore.Http;

namespace Nutritionist.Web.Controllers
{
    public class NutritionistController : BaseController
    {
        public NutritionistController(IMapper mapper) : base(mapper)
        {
        }

        public IActionResult Add()
        {
            return View(ReadOnlyValues.NutritionistAddViewPath);
        }
        [HttpPost]
        public IActionResult Add(NutritionistInsertModel nutritionistInsertModel)
        {

            if (!ModelState.IsValid)
            {
                return Add();
            }
            else
            {
                var userId = HttpContext.Session.GetInt32(ReadOnlyValues.UserIdSession);
                if (!userId.HasValue)
                {
                    return View(ReadOnlyValues.HomeLoginViewPath);
                }
                nutritionistInsertModel.UserId = userId.Value;
                var nutritionistInsertModels = PostMultipartForm<bool>(MyApiRequestModel.PostNutritionistRegister, nutritionistInsertModel);
                var checkNutritionistInsertBaseResponseError = CheckBaseControllerError(nutritionistInsertModels);
                if (checkNutritionistInsertBaseResponseError == null)
                {
                    return View(ReadOnlyValues.HomeLoginViewPath);
                }
                else
                {
                    return Error(checkNutritionistInsertBaseResponseError);
                }
            }

        }
        public IActionResult List()
        {
            var nutritionistListModels = Get<List<NutritionistListModel>>(MyApiRequestModel.GetNutritionistsList, false);
            var checkNutBaseResponseError = CheckBaseControllerError(nutritionistListModels);

            if (checkNutBaseResponseError == null)
            {
                return View(ReadOnlyValues.NutritionistListViewPath, nutritionistListModels.tobject);
            }
            else
            {
            }
                return Error(checkNutBaseResponseError);
        }

        public IActionResult Detail(int id)
        {
            var nutDetailBaseModels = Get<NutritionistDetailModel>(MyApiRequestModel.GetNutritionistDetail, false, id.ToString());
            var checkNutBaseResponseError=CheckBaseControllerError(nutDetailBaseModels);
            if (checkNutBaseResponseError == null)
            {
                var commentListBaseModels = Get<List<CommentListModel>>(MyApiRequestModel.GetCommentList, false, nutDetailBaseModels.tobject.Id.ToString());
                var checkCommentBaseResponseError = CheckBaseControllerError(nutDetailBaseModels);
                var articleListBaseModels = Get<List<ArticleListModel>>(MyApiRequestModel.GetNutritionistArticlesList, false, nutDetailBaseModels.tobject.Id.ToString());
                var checkArticleBaseResponseError = CheckBaseControllerError(articleListBaseModels);
                if (checkCommentBaseResponseError == null && checkArticleBaseResponseError == null)
                {
                    NutritionistContDetailModel nutritionistContDetailModel = 
                        new NutritionistContDetailModel(commentListBaseModels.tobject,articleListBaseModels.tobject,nutDetailBaseModels.tobject);
                    return View(ReadOnlyValues.NutritionistDetailViewPath, nutritionistContDetailModel);
                }
                else
                {
                    return Error(checkCommentBaseResponseError, checkArticleBaseResponseError);
                }

            }
            else
            {
                return Error(checkNutBaseResponseError);
            }
        }
        public IActionResult AddArticle()
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            return View(ReadOnlyValues.NutritionistAddArticleViewPath);
        }
        [HttpPost]
        public IActionResult AddArticle(ArticleInsertModel articleInsertModel)
        {
            if (ModelState.IsValid)
            {
                var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
                if (!nutritionistId.HasValue)
                {
                    return View(ReadOnlyValues.HomeLoginViewPath);
                }
                articleInsertModel.NutritionistId = nutritionistId.Value;
                var articleInsertModels = PostMultipartForm<bool>(MyApiRequestModel.PostArticleAdd, articleInsertModel, true);
                var checkArticleInsertBaseResponseError = CheckBaseControllerError(articleInsertModels);

                if (checkArticleInsertBaseResponseError == null)
                {
                    return Detail(articleInsertModel.NutritionistId);
                }
                else if (!ModelState.IsValid)
                {
                    return AddArticle();
                }
                else
                {
                    return Error(checkArticleInsertBaseResponseError);
                }
            }
            else
            {
                return AddArticle();
            }
            
        }

        [HttpPost]
        public IActionResult AddComment(String commentContent, String nutritionistId)
        {
            var userId = HttpContext.Session.GetInt32(ReadOnlyValues.UserIdSession);
            if (!userId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            int nutritionistIdInt = Int32.Parse(nutritionistId);
            if (String.IsNullOrEmpty(commentContent)|| nutritionistIdInt < 0 || commentContent.Trim().Length <= 0)
            {
                return Detail(nutritionistIdInt);
            }
            else
            {
                CommentInsertModel comment = new CommentInsertModel() {
                    CommentContent = commentContent,
                    NutritionstId = nutritionistIdInt,
                    UserId = userId.Value,
                };
                var commentInsertModels = Post<bool>(MyApiRequestModel.PostAddComment, comment,withToken:true);
                var checkCommentInsertBaseResponseError = CheckBaseControllerError(commentInsertModels);
                if (checkCommentInsertBaseResponseError == null)
                {
                    return Detail(nutritionistIdInt);
                }
                else
                {
                    return Error(checkCommentInsertBaseResponseError);
                }
            }
        }

        [HttpGet]
        public IActionResult Edit()
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            var nutDetailResponse = Get<NutritionistDetailModel>(MyApiRequestModel.GetNutritionistDetail, false, nutritionistId.Value.ToString());
            var checkNutDetailBaseControllerError = CheckBaseControllerError(nutDetailResponse);
            if (checkNutDetailBaseControllerError == null)
            {
                var nutUpdateModel= mapper.Map<NutritionistDetailModel, NutritionistUpdateModel>(nutDetailResponse.tobject);
                return View("~/Views/Nutritionist/Edit.cshtml", nutUpdateModel);
            }
            else
            {
                return Error(checkNutDetailBaseControllerError);
            }
        }

        [HttpPost]
        public IActionResult Edit(NutritionistUpdateModel nutritionistUpdateModel)
        {
            if (ModelState.IsValid)
            {
                var editRes = PostMultipartForm<bool>(MyApiRequestModel.PostEditNutritionist, nutritionistUpdateModel,true);
                var checkEditBaseControllerError = CheckBaseControllerError(editRes);
                if (checkEditBaseControllerError == null)
                {
                    return Detail(nutritionistUpdateModel.Id);
                }
                else
                {
                    return Error(checkEditBaseControllerError);
                }
            }
            else
            {
                return Edit();
            }

        }
        public IActionResult Delete()
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            if (nutritionistId.Value >= 0)
            {

Nutritionist/Nutritionist.Web/Views/Article/Detail.cshtml
@model Nutritionist.Core.Models.Article.Detail
@using Newtonsoft.Json;

@{
    ViewData["Title"] = "Detail";
    Layout = "~/Views/Shared/_Layout.cshtml";
    


}



<section class="image1 cid-snKxmdOxCx" id="image1-1a">

    <div class="container">
        <div class="row align-items-center">
            <div class="col-12 col-lg-6">
                <div class="image-wrapper">
                    @if (Model.Image != null)
                    {
                        <img src="data:image/jpg;base64, @Convert.ToBase64String(Model.Image)">
                    }
                    <p class="mbr-description mbr-fonts-style pt-2 align-center display-4"></p>
                </div>
            </div>
            <div class="col-12 col-lg">
                <center class="text-wrapper">
                    <h3 class="mbr-section-title mbr-fonts-style mb-3 display-5">
                        <strong>@Model.Title</strong>
                    </h3>

                    <div class="row pt-1">

                        <div class="container">
                            <i>@Model.UpdateDate.ToString("MM/dd/yyyy")</i>
                        </div>
                        <div class="container pt-3">
                            <a class="beautyLink" asp-action="Detail" asp-controller="Nutritionist" asp-route-id=@Model.NutritionistId.ToString()>
                                @Model.Nutritionist.User.ToString()
                            </a>
                        </div>
                    </div>

                </center>
            </div>
        </div>
    </div>
</section>

<section class="content5 cid-snKxuM5n0n" id="content5-1b">

    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-12 col-lg-10">

                <h4 class="mbr-section-subtitle mbr-fonts-style mb-4 display-5"></h4>
                <p class="mbr-text mbr-fonts-style display-7" style="white-space:pre-wrap">
                    @Html.Raw(Model.Body)
                </p>
            </div>
        </div>
    </div>
</section>

Nutritionist/Nutritionist.Web/Views/Article/Edit.cshtml
@model Nutritionist.Core.Models.Article.Update
@{
    ViewData["Title"] = "Makale Güncelleme";
    Layout = "~/Views/Shared/_Layout.cshtml";
    byte[] articleImage = Nutritionist.Web.Infrastructure.StaticFunctions.GetBytesFromFile(Model.Image);

}

<section class="form5 cid-smbjZuFWDN" id="form5-q">


    <div class="container">
        <div class="mbr-section-head">
            <h3 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2">
                <strong>Makaleni Güncelle</strong>
            </h3>

        </div>
        <div class="row justify-content-center mt-4">
            <div class="col-lg-8 mx-auto mbr-form">
                <form asp-controller="Article" asp-action="Edit" method="POST" class="mbr-form form-with-styler" enctype="multipart/form-data">
                    <div class="dragArea row">
                        <div class="form-group">
                            <center>
                                @if (articleImage == null || articleImage.Length <= 0)
                                {
                                    <img src="https://www.generationsforpeace.org/wp-content/uploads/2018/03/empty.jpg" id="Image_Preview" style="width:400px;height:300px">
                                }
                                else
                                {
                                    <img src="data:image/jpg;base64, @Convert.ToBase64String(articleImage)" id="Image_Preview">
                                }
                            </center>
                            <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn py-4">
                                <span class="btn btn-warning" id="Image_Btn">
                                    <span>
                                        Makale Resmi
                                    </span>
                                </span>
                                <input type="file" id="Image" asp-for="Image" style="visibility:hidden;">
                            </div>

                        </div>

                        <div class="col-12 form-group mt-3">
                            <label class="control-label">Makale Başlığı</label>
                            <input type="text" placeholder="Makale Başlığı" class="form-control" asp-for="Title">
                            <small class="form-text text-muted">En fazla 150 karakterden oluşmaldır.</small>
                            <span asp-validation-for="Title" class="text-danger"></span>

                        </div>
                        <div class="col-12 form-group mt-3">
                            <label class="control-label">Makale</label>
                            <textarea placeholder="Makale" class="form-control" rows="50" asp-for="Body"></textarea>
                            <span asp-validation-for="Body" class="text-danger"></span>

                        </div>

                        <div class="col-lg-12 col-md-12 col-sm-12 align-center mbr-section-btn">
                            <button type="submit" class="btn btn-primary display-4">Güncelle</button>
                        </div>
                    </div>
                </form>
                <hr>
                <center>
                    <a asp-controller="Article" asp-action="Delete" asp-route-id="@Model.Id.ToString()" class="btn btn-danger" onclick="return confirm('Makalenizi kaldırmak istediginden emin misin ?',);">Makaleyi Kaldır</a>
                </center>
            </div>
        </div>
    </div>

</section>

Nutritionist/Nutritionist.Web/Views/Article/List.cshtml
@model IEnumerable<Nutritionist.Core.Models.Article.List>

@{
    ViewData["Title"] = "Makaleler";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<section class="gallery3 cid-smamM4w0M4" id="gallery3-9">


        <div class="container-fluid">
            <div class="mbr-section-head">
                <h4 class="mbr-section-title mbr-fonts-style align-center mb-0 display-2"><strong>Beslenme Uzmanlarının Makaleleri</strong></h4>

            </div>
            @Html.Partial("~/Views/Shared/ArticleListPartial.cshtml", Model)
        </div>
</section>