Nutritionist/Nutritionist.Web/Controllers/ArticleController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Nutritionist.Web.Infrastructure;
using ArticleListModel = Nutritionist.Core.Models.Article.List;
using ArticleDetailModel = Nutritionist.Core.Models.Article.Detail;
using ArticleUpdateModel = Nutritionist.Core.Models.Article.Update;
using Nutritionist.Core.Models;
using Nutritionist.Core.Models.ResponseModels;
using AutoMapper;
using Nutritionist.Web.Models;
using Microsoft.AspNetCore.Http;

namespace Nutritionist.Web.Controllers
{
    public class ArticleController : BaseController
    {
        public ArticleController(IMapper mapper) : base(mapper)
        {
        }

        public IActionResult Detail(int id)
        {
            var articleDetailBaseModels = Get<ArticleDetailModel>(MyApiRequestModel.GetArticleDetail, false, id.ToString());
            var checkArticleBaseResponseError = CheckBaseControllerError(articleDetailBaseModels);
            if (checkArticleBaseResponseError == null)
            {
                return View(ReadOnlyValues.ArticleDetailViewPath, articleDetailBaseModels.tobject);
            }
            else
            {
                return Error(checkArticleBaseResponseError);
            }
        }
        public IActionResult NutritionistArticleList(String nutritionistId)
        {
            var nutritionistArticleListModels = Get<List<ArticleListModel>>(MyApiRequestModel.GetNutritionistArticlesList, false, nutritionistId);
            var checkNutArticleListBaseResponseError = CheckBaseControllerError(nutritionistArticleListModels);

            if (checkNutArticleListBaseResponseError == null)
            {
                return View(ReadOnlyValues.NutritionistArticlesViewPath, nutritionistArticleListModels.tobject);
            }
            else
            {
                return Error(checkNutArticleListBaseResponseError);
            }
        }
        public IActionResult List()
        {
            var articleListBaseModels = Get<List<ArticleListModel>>(MyApiRequestModel.GetArticlesList, false);
            var checkArticlesBaseResponseError = CheckBaseControllerError(articleListBaseModels);
            if (checkArticlesBaseResponseError == null)
            {
                return View(ReadOnlyValues.ArticleListViewPath, articleListBaseModels.tobject);
            }
            else
            {
                return Error(checkArticlesBaseResponseError);
            }
        }

        [HttpGet]
        public IActionResult Edit(String id)
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            var articleDetailResponse = Get<ArticleDetailModel>(MyApiRequestModel.GetArticleDetail, false, id);
            var checkArticleDetailBaseControllerError = CheckBaseControllerError(articleDetailResponse);
            if (checkArticleDetailBaseControllerError == null)
            {
                var articleUpdateModel = mapper.Map<ArticleDetailModel, ArticleUpdateModel>(articleDetailResponse.tobject);
                return View(ReadOnlyValues.ArticleEditViewPath, articleUpdateModel);
            }
            else
            {
                return Error(checkArticleDetailBaseControllerError);
            }
        }

        [HttpPost]
        public IActionResult Edit(ArticleUpdateModel articleUpdateModel)
        {
            if (ModelState.IsValid)
            {
                var editRes = PostMultipartForm<bool>(MyApiRequestModel.PostArticleEdit, articleUpdateModel,true);
                var checkEditBaseControllerError = CheckBaseControllerError(editRes);
                if (checkEditBaseControllerError == null)
                {
                    return Detail(articleUpdateModel.Id);
                }
                else
                {
                    return Error(checkEditBaseControllerError);
                }
            }
            else
            {
                return Edit(articleUpdateModel.Id.ToString());
            }

        }
        public IActionResult Delete(String id)
        {
            var nutritionistId = HttpContext.Session.GetInt32(ReadOnlyValues.NutritionistIdSession);
            if (!nutritionistId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            else
            {
                var articleDeleteResponse = Delete<bool>(MyApiRequestModel.DeleteArticle, true, id);
                var checkArticleDeleteBaseControllerError = CheckBaseControllerError(articleDeleteResponse);
                if (checkArticleDeleteBaseControllerError == null)
                {

                    return NutritionistArticleList(nutritionistId.Value.ToString());
                }
                else
                {
                    return Error(checkArticleDeleteBaseControllerError);
                }
            }

        }
    }
}

Nutritionist/Nutritionist.Web/Controllers/UserController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AutoMapper;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Nutritionist.Core.Models;
using Nutritionist.Web.Infrastructure;
using Nutritionist.Web.Models;
using UserDetail = Nutritionist.Core.Models.User.Detail;
using UserUpdate = Nutritionist.Core.Models.User.Update;

namespace Nutritionist.Web.Controllers
{
    public class UserController : BaseController
    {
        public UserController(IMapper mapper) : base(mapper)
        {
        }

        [HttpGet]
        public IActionResult Edit()
        {
            var userId = HttpContext.Session.GetInt32(ReadOnlyValues.UserIdSession);
            if (!userId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            var userDetailResponse=Get<UserDetail>(MyApiRequestModel.GetUserDetail,false, userId.Value.ToString());
            var checkUserDetailBaseControllerError = CheckBaseControllerError(userDetailResponse);
            if (checkUserDetailBaseControllerError == null)
            {
                var userUpdateModel = mapper.Map<UserDetail, UserUpdate>(userDetailResponse.tobject);
                return View(ReadOnlyValues.UserEditViewPath, userUpdateModel);
            }
            else
            {
                return Error(checkUserDetailBaseControllerError);
            }
        }

        [HttpPost]
        public IActionResult Edit(UserUpdate userUpdate) 
        {
            if (ModelState.IsValid)
            {
                var editRes = Post<bool>(MyApiRequestModel.PostEditUser, userUpdate, withToken: true);
                var checkEditBaseControllerError = CheckBaseControllerError(editRes);
                if (checkEditBaseControllerError == null)
                {
                    return View(ReadOnlyValues.HomeLoginViewPath);
                }
                else
                {
                    return Error(checkEditBaseControllerError);
                }
            }
            else
            {
                return Edit();
            }

        }
       
        public IActionResult Delete()
        {
            var userId = HttpContext.Session.GetInt32(ReadOnlyValues.UserIdSession);
            if (!userId.HasValue)
            {
                return View(ReadOnlyValues.HomeLoginViewPath);
            }
            else
            {
                if (userId.Value >= 0)
                {
                    var userDeleteResponse = Delete<bool>(MyApiRequestModel.DeleteUser, true, userId.Value.ToString());
                    var checkUserDeleteBaseControllerError = CheckBaseControllerError(userDeleteResponse);
                    if (checkUserDeleteBaseControllerError == null)
                    {

                        return View(ReadOnlyValues.HomeLoginViewPath);
                    }
                    else
                    {
                        return Error(checkUserDeleteBaseControllerError);
                    }
                }
                else
                {
                    return Error(ErrorViewModel.GetDefaultException);
                }
            }

            
        }
        
    }
}

Nutritionist/Nutritionist.Web/Views/Shared/ArticleListPartial.cshtml
@model IEnumerable<Nutritionist.Core.Models.Article.List>
@using Microsoft.AspNetCore.Http;

@{
    
    int userIdSession = -1, nutritionistIdSession = -1;
    if (Context.Session.GetInt32("UserId").HasValue)
    {
        userIdSession = Context.Session.GetInt32("UserId").Value;
    }
    if (Context.Session.GetInt32("NutId").HasValue)
    {
        nutritionistIdSession = Context.Session.GetInt32("NutId").Value;
    }
}

<div class="row mt-5 pt-3">
    @if (Model != null)
    {
        @foreach (var item in Model)
        {
            <div class="item features-image сol-12 col-md-6 col-lg-3">
                <div class="item-wrapper">
                    @if (item.Image != null && item.Image.Length > 0)
                    {
                        <div class="item-img">
                            <img src="data:image/jpg;base64, @Convert.ToBase64String(item.Image)">
                        </div>
                    }
                    <div class="item-content">
                        <h5 class="item-title mbr-fonts-style display-7">
                            <strong>@item.Title</strong>
                        </h5>

                        <p class="mbr-text mbr-fonts-style mt-3 display-7">
                            @if ((item.Image != null && item.Image.Length > 0) && item.Body.Length > 105)
                            {
                                @item.Body.Substring(0, 100)
                            }
                            else if (item.Body.Length > 255)
                            {
                                @item.Body.Substring(0, 250)
                            }
                            else
                            {
                                @item.Body
                            }
                            <a asp-action="Detail" asp-controller="Article" asp-route-id=@item.Id.ToString() class="text-primary">
                                Devamını Oku..
                            </a>
                        </p>
                    </div>
                    <div class="item-content">
                        @if (nutritionistIdSession == item.NutritionistId)
                        {
                            <div style="position: absolute;bottom: 0;left: 0;">
                                <a asp-controller="Article" asp-action="Edit" asp-route-id="@item.Id.ToString()" class="btn btn-warning">Makaleyi Düzenle</a>
                            </div>
                        }
                        <div class="m-3" style="position: absolute;bottom: 0;right: 0;">
                            <i>@item.UpdateDate.Date.ToString("dd MMMM yyyy")</i>
                        </div>
                    </div>
                </div>
            </div>
        }
    }
</div>

Nutritionist/Nutritionist.Web/Views/Shared/_Footer.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
    <section class="footer3 cid-smamuFMZsy" once="footers" id="footer3-7">
        <div class="container">
            <div class="media-container-row align-center mbr-white">
                <div class="row row-links">
                    <ul class="foot-menu">
                        <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">About us</a>
                        </li>
                        <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Services</a>
                        </li>
                        <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Contact Us</a>
                        </li>
                        <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Careers</a>
                        </li>
                        <li class="foot-menu-item mbr-fonts-style display-7">
                            <a class="text-white" href="#" target="_blank">Work</a>
                        </li>
                    </ul>
                </div>
                <div class="row social-row">
                    <div class="social-list align-right pb-2">

                        <div class="soc-item">
                            <a asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-twitter socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-facebook socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-youtube socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-instagram socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-googleplus socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div><div class="soc-item">
                            <a  asp-controller="Home" asp-action="Index" target="_blank">
                                <span class="socicon-behance socicon mbr-iconfont mbr-iconfont-social"></span>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="row row-copirayt">
                    <p class="mbr-text mb-0 mbr-fonts-style mbr-white align-center display-7">
                        © Copyright 2021 Beslenme Uzmanım. All Rights Reserved.
                    </p>
                </div>
            </div>
        </div>
    </section>

Nutritionist/Nutritionist.Web/Views/Shared/_Header.cshtml
@using Microsoft.AspNetCore.Http;
@{
    int userIdSession = -1, nutritionistIdSession = -1;
    if (Context.Session.GetInt32("UserId").HasValue)
    {
        userIdSession = Context.Session.GetInt32("UserId").Value;
    }
    if (Context.Session.GetInt32("NutId").HasValue)
    {
        nutritionistIdSession = Context.Session.GetInt32("NutId").Value;
    }
}
<section class="menu menu2 cid-smalfSdkTh" once="menu" id="menu2-1">

    <nav class="navbar navbar-dropdown navbar-fixed-top navbar-expand-lg">
        <div class="container">
            <div class="navbar-brand">
                <span class="navbar-logo">
                    <a asp-action="Index" asp-controller="Home">
                        <img src="~/assets/images/mbr.png" alt="Mobirise" style="height: 3.9rem;">
                    </a>
                </span>
                <span class="navbar-caption-wrap"><a class="navbar-caption text-black display-7" asp-action="Index" asp-controller="Home" >Beslenme Uzmanım</a></span>
            </div>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
                <div class="hamburger">
                    <span></span>
                    <span></span>
                    <span></span>
                    <span></span>
                </div>
            </button>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav nav-dropdown" data-app-modern-menu="true">
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" asp-action="Index" asp-controller="Home">
                            Ana Sayfa
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" asp-action="List" asp-controller="Nutritionist">
                            Diyet Uzmanları
                        </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link link text-black display-4" asp-action="List" asp-controller="Article">
                            Makaleler
                        </a>
                    </li>
                </ul>
                @if (nutritionistIdSession == -1)
                {
                    <div class="navbar-buttons mbr-section-btn">
                        @if (userIdSession == -1)
                        {
                            <a class="btn btn-info display-4" asp-action="UserRegister" asp-controller="Home">
                                Kayıt Ol
                            </a>
                            <a class="btn btn-warning display-4" asp-action="Login" asp-controller="Home">
                                Giriş Yap
                            </a>
                        }
                        else
                        {
                            <a class="btn btn-info display-4" asp-action="Add" asp-controller="Nutritionist">
                                Klinik Oluştur
                            </a>
                        }

                    </div>
                }

                @if (userIdSession != -1)
                {
                    <div class="btn-group">
                        <button type="button" class="btn btn-warning dropdown-toggle" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                            Seçenekler
                        </button>
                        <div class="dropdown-menu">
                            @if (nutritionistIdSession != -1)
                            {
                                <a class="dropdown-item" asp-action="Detail" asp-controller="Nutritionist" asp-route-id=@nutritionistIdSession.ToString()>Profil</a>
                                <a class="dropdown-item" asp-action="NutritionistArticleList" asp-controller="Article" asp-route-nutritionistId=@nutritionistIdSession.ToString()>Makalelerim</a>
                                <a class="dropdown-item" asp-action="AddArticle" asp-controller="Nutritionist">Makaleni Oluştur</a>
                                <a class="dropdown-item" asp-action="Edit" asp-controller="Nutritionist">Klinik Güncelle</a>
                            }
                            <a class="dropdown-item" asp-action="Edit" asp-controller="User">Bilgilerimi Güncelle</a>
                            <center>
                                <a asp-controller="User" asp-action="Delete" class="btn btn-outline-danger  m-2 px-3 py-2" onclick="return confirm('Hesabını kaldırmak istediginden emin misin ?',);"><i class="fas fa-trash-alt text-white"></i>Hesabı Kaldır</a>
                            </center>
                            @if (nutritionistIdSession != -1)
                            {
                                <center>
                                    <a asp-controller="Nutritionist" asp-action="Delete" class="btn btn-outline-secondary  m-2 px-3 py-2" onclick="return confirm('Klinigini kaldırmak istediginden emin misin ?',);"><i class="fas fa-trash-alt text-white"></i>Klinigi Kaldır</a>
                                </center>
                            }
                            <div class="dropdown-divider"></div>
                            <a class="dropdown-item" asp-action="LogOut" asp-controller="Home">Çıkış Yap</a>
                        </div>
                    </div>
                }
            </div>
        </div>
    </nav>
</section>

Nutritionist/Nutritionist.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <style>
        label {
            color: rgb(76, 175, 80);
        }
    </style>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.2.0, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="~/assets/images/mbr.png" type="image/x-icon">
    <meta name="description" content="">

    <title> @ViewData["Title"] </title>
    <link rel="stylesheet" href="~/css/site.css">
    <link rel="stylesheet" href="~/assets/tether/tether.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="preload" as="style" href="~/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">




</head>
<body>
    @Html.Partial("_Header")

    @RenderBody()

    @Html.Partial("_Footer")

    <section style="background-color: #fff; font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', 'Roboto', 'Helvetica Neue', Arial, sans-serif; color:#aaa; font-size:12px; padding: 0; align-items: center; display: flex;"><a href="https://mobirise.site/q" style="flex: 1 1; height: 3rem; padding-left: 1rem;"></a><p style="flex: 0 0 auto; margin:0; padding-right:1rem;"><a href="https://mobirise.site/t" style="color:#aaa;">Built</a> with Mobirise bootstrap web template</p></section>
    <script src="~/assets/web/assets/jquery/jquery.min.js"></script>
    <script src="~/js/site.js"></script>
    <script src="~/assets/popper/popper.min.js"></script>
    <script src="~/assets/tether/tether.min.js"></script>
    <script src="~/assets/bootstrap/js/bootstrap.min.js"></script>
    <script src="~/assets/smoothscroll/smooth-scroll.js"></script>
    <script src="~/assets/dropdown/js/nav-dropdown.js"></script>
    <script src="~/assets/dropdown/js/navbar-dropdown.js"></script>
    <script src="~/assets/touchswipe/jquery.touch-swipe.min.js"></script>
    <script src="~/assets/countdown/jquery.countdown.min.js"></script>
    <script src="~/assets/theme/js/script.js"></script>
    <script src="~/assets/formoid/formoid.min.js"></script>


</body>
</html>

Nutritionist/Nutritionist.Web/Views/Shared/_SimpleLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <!-- Site made with Mobirise Website Builder v5.2.0, https://mobirise.com -->
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="generator" content="Mobirise v5.2.0, mobirise.com">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimum-scale=1">
    <link rel="shortcut icon" href="~/assets/images/mbr.png" type="image/x-icon">
    <meta name="description" content="">


    <title> @ViewData["Title"] </title>
    <link rel="stylesheet" href="~/assets/tether/tether.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-grid.min.css">
    <link rel="stylesheet" href="~/assets/bootstrap/css/bootstrap-reboot.min.css">
    <link rel="stylesheet" href="~/assets/dropdown/css/style.css">
    <link rel="stylesheet" href="~/assets/socicon/css/styles.css">
    <link rel="stylesheet" href="~/assets/theme/css/style.css">
    <link rel="preload" as="style" href="~/assets/mobirise/css/mbr-additional.css">
    <link rel="stylesheet" href="~/assets/mobirise/css/mbr-additional.css" type="text/css">



</head>
<body>
    @RenderBody()
</body>
</html>